import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css";
//import Logo from "../components/logo.js";
import { getServerSession } from "next-auth";
import SessionProvider from "@/app/db/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Added some code to this so that every page is able to access current client session and get info from it
export default async function RootLayout({children}){
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionProvider session={session}>
        {/* <h1><Logo /></h1> */}
        {children}
      </SessionProvider>
      </body>
    </html>
  );
}